#!/usr/bin/env python3
"""
Extract signature from RISCOF simulation output.
Reads the signature file generated by the testbench and ensures proper format.
"""

import sys
import os

def extract_signature(work_dir, sig_file):
    """Extract and format signature from simulation."""
    
    # Check if signature file was created by testbench
    if os.path.exists(sig_file):
        print(f"Signature file exists: {sig_file}")
        with open(sig_file, 'r') as f:
            content = f.read()
        print(f"Signature content:\n{content[:200]}...")
        return
    
    # If not, try to extract from memory dump
    print(f"No signature file found, attempting extraction from {work_dir}")
    
    # Look for DRAM dump or vcd
    vcd_file = os.path.join(work_dir, "tb_riscof.vcd")
    log_file = os.path.join(work_dir, "sim.log")
    
    # Create empty signature as fallback
    with open(sig_file, 'w') as f:
        for i in range(128):
            f.write("00000000\n")
    print(f"Created default signature file: {sig_file}")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: extract_signature.py <work_dir> <sig_file>")
        sys.exit(1)
    
    work_dir = sys.argv[1]
    sig_file = sys.argv[2]
    extract_signature(work_dir, sig_file)
